version: 2.1
orbs:
  jq: "circleci/jq@2.2.0"
  shellcheck: "circleci/shellcheck@2.2.0"
  slack: "circleci/slack@4.3.3"

executors:
  standard:
    parameters:
      image:
        description: "docker image"
        default: "cimg/base:stable-18.04"
        type: string
      class:
        description: "resource class"
        default: "small"
        type: string
    docker:
    - image: <<parameters.image>>
      auth:
        username: $DOCKER_LOGIN
        password: $DOCKER_PASSWORD
    resource_class: <<parameters.class>>
    environment:
      LC_ALL: "en_US.UTF-8"

  adhoc-machine:
    parameters:
      class:
        description: "resource class"
        default: "medium"
        type: string
    machine:
      image: "ubuntu-2004:202104-01"
    resource_class: <<parameters.class>>
    environment:
      LC_ALL: "en_US.UTF-8"

commands:
  workattach:
    steps:
      - attach_workspace:
          at: /tmp/workspace
  docs_deps:
    description: "Download dependencies for rendering docs"
    steps:
      - run: |
          sudo add-apt-repository -y ppa:plt/racket \
              && sudo apt update \
              && sudo apt install -y --no-install-recommends \
                libcairo2 \
                libfontconfig1 \
                libjpeg62 \
                libpangocairo-1.0 \
                racket \
                python3-setuptools
          (cd pygments && sudo make install)
  slack_fail:
    steps:
      - slack/notify:
          # NOTE: We used to do
          # branch_pattern: "master,gh-pages"
          # But, I am disabling it on purpose
          event: fail
          # XXX make circle_branch a link
          custom: |
            { "blocks": [
                { "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*FAIL* ${CIRCLE_USERNAME}/${CIRCLE_BRANCH} > ${CIRCLE_JOB} <${CIRCLE_BUILD_URL}|more...>" }}]}
  srd_yes:
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
          version: '20.10.6'
  srd_no:
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
          version: '20.10.6'
  restore_bin:
    description: "Restore the build binaries"
    parameters:
      with_srd_no:
        type: boolean
        default: true
    steps:
      - workattach
      - when:
          condition: << parameters.with_srd_no >>
          steps:
            - srd_no
      - run: |
          mkdir -p ~/.local
          ln -sf /tmp/workspace/bin ~/.local/bin
          ls ~/.local/bin/*
          zcat /tmp/workspace/docker/runner.tar.gz | docker load
          source ./VERSION
          docker tag reachsh/runner:latest reachsh/runner:${VERSION}
          docker tag reachsh/runner:latest reachsh/runner:${MAJOR}.${MINOR}
          docker tag reachsh/runner:latest reachsh/runner:${MAJOR}
  restore_img_adhoc_machine:
    description: "Restore ad-hoc machine Docker images"
    steps:
      - run: |
          source ./VERSION
          zcat /tmp/workspace/docker/rpc-server.tar.gz | docker load
          zcat /tmp/workspace/docker/reach.tar.gz      | docker load
          zcat /tmp/workspace/docker/reach-cli.tar.gz  | docker load

          docker tag reachsh/rpc-server:latest reachsh/rpc-server:${VERSION}
          docker tag reachsh/rpc-server:latest reachsh/rpc-server:${MAJOR}.${MINOR}
          docker tag reachsh/rpc-server:latest reachsh/rpc-server:${MAJOR}

          docker tag reachsh/reach:latest      reachsh/reach:${VERSION}
          docker tag reachsh/reach:latest      reachsh/reach:${MAJOR}.${MINOR}
          docker tag reachsh/reach:latest      reachsh/reach:${MAJOR}

          docker tag reachsh/reach-cli:latest  reachsh/reach-cli:${VERSION}
          docker tag reachsh/reach-cli:latest  reachsh/reach-cli:${MAJOR}.${MINOR}
          docker tag reachsh/reach-cli:latest  reachsh/reach-cli:${MAJOR}
  run_example_sh:
    description: "example.sh <<parameters.which>>"
    parameters:
      which:
        type: string
    steps:
      - run: |
          cd examples && ../.circleci/example.sh <<parameters.which>>
  run_example_record:
    description: "Record outcome"
    steps:
      - run:
          when: always
          command: |
            if [ ! -f /tmp/status ] ; then
              echo 'export STATUS="fail"' > /tmp/status
            fi
            cat /tmp/status
            mkdir -p /tmp/workspace/record
            mv /tmp/status /tmp/workspace/record/${CIRCLE_JOB}
  run_example_persist:
    description: "Persist outcome"
    steps:
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - record
  stack_deps:
    description: "Install stack dependencies"
    steps:
      - run: |
          # Install stack deps
          sudo apt update && sudo apt install \
            g++ \
            gcc \
            git \
            gnupg \
            libc6-dev \
            libffi-dev \
            libgmp-dev \
            libtinfo-dev \
            make \
            netbase \
            xz-utils \
            zlib1g-dev
          # Install stack
          if ! [ -f ~/.local/bin/stack ] ; then
            curl -sSL https://get.haskellstack.org/ | sh -s - -d ~/.local/bin
          fi
          # Reset locale
          sudo sh -c 'echo "LC_ALL=en_US.UTF-8" >> /etc/environment \
                   && echo "en_US.UTF-8 UTF-8"  >> /etc/locale.gen \
                   && echo "LANG=en_US.UTF-8"    > /etc/locale.conf \
                   && locale-gen en_US.UTF-8'
          # Setup package
          (cd hs && make package.yaml)
      - restore_cache:
         keys:
          - "hs-3-{{ checksum \"hs/stack.yaml\" }}-{{ checksum \"hs/package.yaml\" }}"
      - run: |
          # Install deps
          (cd hs && make hs-deps)
      - save_cache:
          key: "hs-3-{{ checksum \"hs/stack.yaml\" }}-{{ checksum \"hs/package.yaml\" }}"
          paths:
          - ~/.stack
          - "hs/.stack-work"

jobs:
  "docs-render":
    executor: standard
    steps:
    - checkout
    - docs_deps
    - run: |
        (cd docs-src && make render)
        mkdir -p /tmp/workspace/
        cp -fr docs /tmp/workspace/
    - persist_to_workspace:
        root: /tmp/workspace/
        paths:
          - docs
    - slack_fail
  "docs-deploy":
    executor: standard
    steps:
    - checkout
    - workattach
    - add_ssh_keys:
        fingerprints:
        - "83:23:9c:21:6a:74:61:48:20:da:a3:45:79:89:3e:86"
    - run: |
        git config user.email "devbot@reach.sh"
        git config user.name "reachdevbot"
        git fetch origin gh-pages
        git checkout gh-pages
        git pull origin gh-pages
        git rm -r .
        cp -r /tmp/workspace/docs/* .
        [ -f index.html ] || exit 1
        git add .
        # https://stackoverflow.com/questions/8123674/how-to-git-commit-nothing-without-an-error
        git diff-index --quiet HEAD || (git commit -m "[ci skip] docs for ${CIRCLE_SHA1}" && touch .did_change)
        git push origin gh-pages
    - slack_fail
    - run: |
        if [ -f .did_change ]; then
          git diff --exit-code HEAD~ guide-changelog.html
        fi
    - slack/notify:
        event: fail
        channel: 'CMY2TF38D' # general
        # (CMY3E5B3J = reach-lang)
        custom: |
          {
            "blocks": [{
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "<https://docs.reach.sh/guide-changelog.html|Changelog> has changed!"
              }
            }]
          }

  "sh-check":
    executor: standard
    steps:
    - checkout
    - shellcheck/install
    - run: |
        make sh-lint
    - slack_fail
  "build":
    executor:
      name: standard
      class: "medium"
    steps:
    - checkout
    - run: |
        mkdir -p ~/.local /tmp/workspace/bin
        ln -sf /tmp/workspace/bin ~/.local/bin
        # Install mo
        curl -sSLo ~/.local/bin/mo https://git.io/get-mo
        # Install solc
        curl -sSLo ~/.local/bin/solc \
          https://github.com/ethereum/solidity/releases/download/v0.8.5/solc-static-linux
        # Install Z3
        curl -sSLo /tmp/z3.zip \
              https://github.com/Z3Prover/z3/releases/download/z3-4.8.10/z3-4.8.10-x64-ubuntu-18.04.zip \
          && unzip -p /tmp/z3.zip z3-4.8.10-x64-ubuntu-18.04/bin/z3 \
            | cat > ~/.local/bin/z3
        chmod +x ~/.local/bin/*
    - stack_deps
    - srd_yes
    - run: |
        (cd hs && make hs-clean)
        (cd hs && make hs-build)
        (cd hs && make build)
        (cd hs && stack install)
        (cd js && make build)
        (cd js/stdlib && make check)
        mkdir -p /tmp/workspace/docker

        echo 'docker save reachsh/runner:latest...'
        docker save reachsh/runner:latest | gzip > /tmp/workspace/docker/runner.tar.gz

        echo 'docker save reachsh/rpc-server:latest...'
        docker save reachsh/rpc-server:latest | gzip > /tmp/workspace/docker/rpc-server.tar.gz

        echo 'docker save reachsh/reach:latest...'
        docker save reachsh/reach:latest | gzip > /tmp/workspace/docker/reach.tar.gz

        echo 'docker save reachsh/reach-cli:latest...'
        docker save reachsh/reach-cli:latest | gzip > /tmp/workspace/docker/reach-cli.tar.gz
    - persist_to_workspace:
        root: /tmp/workspace/
        paths:
          - bin
          - docker
    - slack_fail
  "hs-test":
    executor:
      name: standard
      class: "medium"
    steps:
    - checkout
    - docs_deps
    - restore_bin
    - stack_deps
    - run:
        command: (cd hs && make hs-test-xml)
        no_output_timeout: 30m
    - store_test_results:
        path: "hs/test-reports"
    - slack_fail
  "hs-check":
    executor: standard
    steps:
    - checkout
    - restore_bin
    - stack_deps
    - run: |
        (cd hs && make hs-check)
    - store_artifacts:
        path: hs/stan.html
    - slack_fail
  "js-test":
    executor: standard
    steps:
    - checkout
    - restore_bin
    - run: |
        (cd js/dockerized-tests && make clean-test && sbin/test.sh)
    - slack_fail
  "example-standard":
    parameters:
      which:
        description: "which example directory"
        type: string
    environment:
      REACH_CI_EXECUTOR: "standard"
    executor: standard
    steps:
    - checkout
    - restore_bin
    - run_example_sh:
        which: << parameters.which >>
    - run_example_record
    - run_example_persist
  "example-adhoc-machine":
    parameters:
      which:
        description: "which example directory"
        type: string
    environment:
      REACH_CI_EXECUTOR: "adhoc-machine"
    executor: adhoc-machine
    steps:
    - checkout
    - restore_bin:
        with_srd_no: false
    - restore_img_adhoc_machine
    - run_example_sh:
        which: << parameters.which >>
    - run_example_record
    - run_example_persist
  "example-sink":
    executor: standard
    steps:
    - checkout
    - workattach
    - run: |
        ./.circleci/record.py >> $BASH_ENV
    - run:
        when: always
        command: |
          echo "${RECORD_MESSAGE}"
    - slack/notify:
        event: always
        # NOTE: We used to do
        # branch_pattern: "master,gh-pages"
        # But, I am disabling it on purpose
        custom: |
          { "blocks": [
              { "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${RECORD_MESSAGE}" }}]}

workflows:
  docs:
    jobs:
    - "docs-render"
    - "docs-deploy":
        filters:
          branches:
            only: master
        requires:
        - "docs-render"
  buildless:
    jobs:
    - "sh-check"
  build:
    jobs:
    - "build"
    - "hs-test":
        requires:
          - "build"
    - "hs-check":
        requires:
          - "build"
    - "js-test":
        requires:
          - "build"
    # Sink and examples follow
